server:
  port: 9090

spring:
  redis:
    host: 192.168.150.106
    port: 6379
    database: 3
#    连接池：一种基于lettuce，一种基于jredis
    lettuce:
      pool:
        max-active: 20 # 最大连接数
        max-idle: 8 # 空闲连接数
        max-wait: -1 #最大等待时间，-1 一直等着
        min-idle: 0

